version: '3.8'

services:
  db:
    image: postgres:16.0
    container_name: flagcamp-db
    environment:
      POSTGRES_DB: temp_db
      POSTGRES_PASSWORD: temp_password
      TZ: UTC
    volumes:
      - flagcamp_pg_local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  flagcamp_pg_local: